name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: "Backend: tests & minimal checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers (chromium)
        working-directory: backend
        run: python -m playwright install chromium

      - name: Run backend tests (pytest)
        working-directory: backend
        run: python -m pytest -q

  frontend:
    name: "Frontend: install & build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Pre-build diagnostics (list frontend source)
        run: |
          echo "Listing src/" && ls -la frontend/src || true
          echo "Listing src/components" && ls -la frontend/src/components || true
          echo "Listing src/components/Pages" && ls -la frontend/src/components/Pages || true
          echo "Case-insensitive search for HomePage.tsx" && find frontend/src -iname "homepage.tsx" -print || true
          echo "Verify HomePage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/HomePage.tsx && echo "OK: HomePage.tsx present" || (echo "Missing: frontend/src/components/Pages/HomePage.tsx" && exit 1)
          echo "Case-insensitive search for DashboardPage.tsx" && find frontend/src -iname "dashboardpage.tsx" -print || true
          echo "Verify DashboardPage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/DashboardPage.tsx && echo "OK: DashboardPage.tsx present" || (echo "Missing: frontend/src/components/Pages/DashboardPage.tsx" && exit 1)
          echo "Case-insensitive search for AuthPage.tsx" && find frontend/src -iname "authpage.tsx" -print || true
          echo "Verify AuthPage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/AuthPage.tsx && echo "OK: AuthPage.tsx present" || (echo "Missing: frontend/src/components/Pages/AuthPage.tsx" && exit 1)
          echo "Case-insensitive search for ProfilePage.tsx" && find frontend/src -iname "profilepage.tsx" -print || true
          echo "Verify ProfilePage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/ProfilePage.tsx && echo "OK: ProfilePage.tsx present" || (echo "Missing: frontend/src/components/Pages/ProfilePage.tsx" && exit 1)
          echo "Case-insensitive search for ScrapingActivityPage.tsx" && find frontend/src -iname "scrapingactivitypage.tsx" -print || true
          echo "Verify ScrapingActivityPage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/ScrapingActivityPage.tsx && echo "OK: ScrapingActivityPage.tsx present" || (echo "Missing: frontend/src/components/Pages/ScrapingActivityPage.tsx" && exit 1)
          echo "Case-insensitive search for HistoryPage.tsx" && find frontend/src -iname "historypage.tsx" -print || true
          echo "Verify HistoryPage.tsx exists (case-sensitive)"
          test -f frontend/src/components/Pages/HistoryPage.tsx && echo "OK: HistoryPage.tsx present" || (echo "Missing: frontend/src/components/Pages/HistoryPage.tsx" && exit 1)

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Run frontend tests (if present)
        if: always()
        working-directory: frontend
        run: |
          if [ -f package.json ] && npm run | grep -q "test"; then
            npm run test --silent || true
          else
            echo "No frontend tests defined"
          fi
